### ISSUE TITLE
Resources should not be hosted on owo

### ISSUE THREAD

**Issue by martmists** [ProjectMonika/Sayori#29]
Despite being reliable, there's no saying in whether the files will remain there forever, and errors may follow caused by anything that could happen to the service.

**Comment by sr229** [comment]
based form what I heard from @deansheather and @aurieh they have no idea which objects are there in store so I don't think it'll be  erased yet.

**Comment by aurieh** [comment]
As long as what you upload does not violate our terms, we won't delete it.

**Comment by sr229** [comment]
Marked as wontfix
